name: Publish to npm
permissions: {}
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: npm install -g corepack
      - run: corepack enable
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn test
      - run: yarn tsc
        if: always()
      - run: yarn biome lint
        if: always()
      - run: yarn version $TAG_NAME
        env:
          TAG_NAME: ${{ github.ref_name }}
      - run: yarn pack -o ./package.tgz
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: tarball
          path: ./package.tgz
  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: tarball
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: npm publish --provenance --access public --tag next ./package.tgz
        if: github.event.release.prerelease
      - run: npm publish --provenance --access public ./package.tgz
        if: ${{ !github.event.release.prerelease }}
